batch_size: 1000 
max_repos: 1
work_nums: 50

libs: ['torch']
lib_names: ['torch']
versions: [['2.0.0', '2.5.0']]

jsonl_switch_dir: 'CodeSync/Data_Demo'    

raw_data_dir: 'CodeSync/Raw_Data'            # metadata saving path
data_dir: 'CodeSync/Data'                    # dataset saving dir
benchmark_dir: 'CodeSync/Benchmark'          # benchmark saving dir
training_set_dir: 'CodeSync/TrainingSet'     # training set saving dir
temp_dir: 'CodeSync/Temp'       

mirror: 'https://pypi.tuna.tsinghua.edu.cn/simple'
llm_api: 'sk-proj-xxx'
llm_url: 'https://api.openai.com/v1'
llm_name: 'gpt-4o-mini'
time_limit: "2024-01-01T00:00:00Z"

token: ["ghp_xxx", "ghp_xxx", "ghp_xxx"]
